name: Reusable Workflow for building container image

on:
  workflow_call:
    inputs:
      name:
        description: 'ECR repo name'
        required: true
        type: string
      dockerfile:
        description: 'Dockerfile name'
        required: false
        type: string
        default: 'Dockerfile'
      context:
        description: 'Build context'
        required: false
        type: string
        default: '.'
      tagPrefix:
        description: 'Image tag prefix'
        required: false
        type: string
        default: ''
      args:
        description: 'Build arguments'
        required: false
        type: string
        default: ''
      preBuildCmd:
        description: 'Pre Build command'
        required: false
        type: string
        default: ''
      secretFile:
        description: 'secret file name'
        required: false
        type: string
        default: ''
      sshFile:
        description: 'ssh key file name'
        required: false
        type: string
        default: ''
    secrets:
      SLACK_WEBHOOK_URL:
        required: true
      SECRET:
        required: false
      SSH_KEY:
        required: false
    outputs:
      tag:
        value: ${{ jobs.build.outputs.tag }}


jobs:
  build:
    name: ${{ github.workflow }} ${{ github.ref_name }}

    outputs:
      tag: ${{ steps.vars.outputs.tag }}

    runs-on:
      - self-hosted
      - builder

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set vars
        id: vars
        run: |
          ref=$(echo -n ${{ github.ref_name }} | tr '/' '-')
          if [[ "${{ github.ref_type }}" == "tag" ]]
          then
            tag="${{ inputs.tagPrefix }}${ref}"
          else
            tag="${{ inputs.tagPrefix }}${ref}-${{ github.sha }}"
          fi
          echo "::set-output name=tag::${tag}"

      - name: Create secret file
        id: set-secret
        if: ${{ inputs.secretFile }}
        run: |
          echo "${{ secrets.SECRET }}" > ${{ inputs.secretFile }}
          chmod 600 ${{ inputs.secretFile }}

      - name: Create ssh key file
        id: set-ssh-key
        if: ${{ inputs.sshFile }}
        run: |
          echo "${{ secrets.SSH_KEY }}" > ${{ inputs.sshFile }}
          chmod 600 ${{ inputs.sshFile }}

      - name: Run pre-build command
        id: pre-build
        if: ${{ inputs.preBuildCmd }}
        run: ${{ inputs.preBuildCmd }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          DOCKER_BUILDKIT: 1
          BUILDKIT_PROGRESS: plain
          DOCKER_DRIVER: overlay2
          ECR_REPO: ${{ steps.login-ecr.outputs.registry }}/${{ inputs.name }}
        run: |
          docker build \
            ${{ inputs.args }} \
            --tag ${ECR_REPO}:${{ steps.vars.outputs.tag }} \
            --file ${{ inputs.dockerfile }} ${{ inputs.context }}
          docker push --all-tags ${ECR_REPO}

      - name: Notify
        uses: 8398a7/action-slack@v3
        if: always()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,job,took
          job_name: '${{ github.workflow }} ${{ github.ref_name }}'
          author_name: 'Started by ${{ github.actor }}'
